---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: github-runners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      volumes:
        - name: containerdsock
          hostPath:
            path: /run/containerd/containerd.sock
        - name: workdir
          hostPath:
            path: /tmp/github-runner-kubernetes
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: runner
          image: ghcr.io/travishepworth/kubernetes/github-runner:latest
          env:
            - name: START_DOCKER_SERVICE
              value: "true"
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-runner
                  key: ACCESS_TOKEN
            - name: RUNNER_SCOPE
              value: "repo"
            - name: REPO_URL
              value: "https://github.com/travishepworth/kubernetes"
            - name: LABELS
              value: build,test,deploy
            - name: RUNNER_NAME_PREFIX
              value: epic-
            - name: RUNNER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RUNNER_WORKDIR
              value: /tmp/github-runner-kubernetes
          volumeMounts:
            - name: containerdsock
              mountPath: /run/containerd/containerd.sock
            - name: workdir
              mountPath: /tmp/github-runner-kubernetes
          securityContext:
            privileged: true  # Required if you're enabling docker
          resources:
            limits:
              cpu: 2
              memory: 512Mi
            requests:
              cpu: 2
              memory: 256Mi
