---
name: Deploy Application
on:
  push:
    branches:
      - main
    paths:
      - "apps/**"
  workflow_dispatch:
jobs:
  deploy:
    name: Apply Kubernetes Manifests
    runs-on: [deploy]
    permissions:
      contents: read
      id-token: write
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: true
          persistent-credentials: false

      - name: Get changes
        id: changes
        run: |

          echo "Checking changed directories in /apps/"

          # Use GitHub context correctly
          if git rev-parse "${{ github.event.before }}" >/dev/null 2>&1; then
            diff_base="${{ github.event.before }}"
          else
            diff_base="HEAD^"
          fi

          echo "Diff base is $diff_base"
          changed_dirs=$(git diff --name-only "$diff_base" "${{ github.sha }}" | grep '^apps/' | awk -F/ '{print $1"/"$2}' | sort -u)

          if [ -z "$changed_dirs" ]; then
            echo "No changes in /apps/, exiting."
            echo "changed=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "$changed_dirs" > changed_dirs.txt
          echo "Changed directories:"
          cat changed_dirs.txt
          echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Apply
        if: steps.changes.outputs.changed == 'true'
        run: |
          while read -r dir; do
            echo "Applying kustomize in $dir"
            kubectl apply -k $dir
          done < changed_dirs.txt
