---
name: Lint
on:
  push:
  workflow_dispatch:
jobs:
  lint:
    name: Lint
    runs-on: [lint]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_SECRET }}

      - name: Pull Image
        run: |
          IMAGE="ghcr.io/travishepworth/kubernetes/linter:latest"
          docker pull $IMAGE || true

      - name: Run Linter
        run: |
          # Run the container to lint
          echo "Running linter..."
          docker run --rm \
            -v "${GITHUB_WORKSPACE}:/workspace:rw" \
            ghcr.io/travishepworth/kubernetes/linter:latest \
            /bin/sh -c "
              cd /workspace &&
              echo 'Running shellcheck...' &&
              find . -type f -name '*.sh' -exec shellcheck {} + || true &&
              echo 'Running yamllint...' &&
              find . -type f \( -name '*.yaml' -o -name '*.yml' \) -exec yamllint {} + || true &&
              echo 'Running kubeconform...' &&
              find . -type f \( -name '*.yaml' -o -name '*.yml' \) -exec kubeconform -strict {} + || true
            "
        shell: bash
