# ---
# name: Lint
# on:
#   push:
#   workflow_dispatch:
# jobs:
#   lint:
#     name: MegaLinter
#     runs-on: [lint]
#
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#
#       - name: Run MegaLinter
#         uses: oxsecurity/megalinter@v7
