---
name: Mirror Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    name: Mirror to GitHub
    runs-on: [git-ops]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Mirror to Public
        env:
          TOKEN: ${{ secrets.PUSH_MIRROR_TOKEN }}
        run: |
          echo "Token Length: ${#TOKEN}"
          git remote remove mirror 2>/dev/null || true
          git remote add mirror https://x-access-token:${TOKEN}@github.com/travishepworth/kubernetes-public.git
          git push --force mirror HEAD:main
