---
name: Mirror Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    name: Mirror to GitHub
    runs-on: [git-ops]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_MIRROR_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Mirror to Public
        run: |
          git remote remove mirror 2>/dev/null || true
          git remote add mirror git@github.com:travishepworth/kubernetes-public.git
          git push --force mirror HEAD:main
